
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONPATH: .
      DB_NAME: ${TEST_DB_NAME}
      DB_USER: ${TEST_DB_USER}
      DB_PASSWORD: ${TEST_DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${TEST_DB_PORT}
    command: >
      sh -c "pytest"

volumes:
  postgres_test_data:
