# Generated by Django 5.1.5 on 2025-01-24 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_admin', models.BooleanField(default=False)),
                ('account_username', models.CharField(max_length=150, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_surname', models.CharField(max_length=100)),
                ('account_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('account_verified', models.BooleanField(default=False)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('account_updated_at', models.DateTimeField(auto_now=True)),
                ('account_last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('role_created_at', models.DateTimeField(auto_now_add=True)),
                ('role_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_name', models.CharField(max_length=255)),
                ('questionnaire_type', models.CharField(max_length=50)),
                ('questionnaire_category', models.CharField(max_length=50)),
                ('questionnaire_language', models.JSONField(default=list)),
                ('questionnaire_description', models.TextField()),
                ('questionnaire_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('questionnaire_created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('questionnaire_accounts', models.ManyToManyField(related_name='questionnaires', to='kyc.account')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255)),
                ('question_description', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('question_created_at', models.DateTimeField(auto_now_add=True)),
                ('question_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_questionnaires',
            field=models.ManyToManyField(related_name='accounts', to='kyc.questionnaire'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField()),
                ('response_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.account')),
                ('response_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.question')),
                ('response_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.role'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.account')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=150, unique=True)),
                ('admin_password', models.CharField(max_length=128)),
                ('admin_created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_last_login', models.DateTimeField(blank=True, null=True)),
                ('admin_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kyc.account')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.role')),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kyc.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kyc.user'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.user')),
            ],
        ),
    ]
